pipeline {
    agent any

    stages {
        stage('Checkout SCM') {
            steps {
                echo 'Checking out code...'
            }
        }

        stage('Build') {
            steps {
                echo 'Building application...'
            }
        }

        stage('Deploy Backend') {
            steps {
                echo 'Deploying backend...'
            }
        }

        stage('Deploy NGINX') {
            steps {
                echo 'Deploying NGINX...'
            }
        }
    }
}
